name: MAUI Unit Tests
 
on:
  push:
    branches:
      - main
      - infra/runner-toevoegen
  pull_request:
    branches:
      - main
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Haal de repository op
        uses: actions/checkout@v4
 
      - name: Installeer .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
 
      - name: Installeer MAUI workloads
        run: dotnet workload install maui-android
 
      - name: Herstel afhankelijkheden (alleen Android en .NET 8)
        run: |
          dotnet restore Grocery.App/Grocery.App.csproj -p:TargetFramework=net8.0-android
          dotnet restore Grocery.Core/Grocery.Core.csproj -p:TargetFramework=net8.0
          dotnet restore Grocery.Core.Data/Grocery.Core.Data.csproj -p:TargetFramework=net8.0
 
      - name: Bouw de applicatie
        run: dotnet build --configuration Release --no-restore
 
      - name: Voer unit tests uit
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal
